name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.1, 8.0, 7.4]
        laravel: [8.*, 7.*, 6.*]
        statamic: [3.2.*]
        os: [ubuntu-latest]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*
        exclude:
          - laravel: 8.*
            php: 7.2
          - laravel: 7.*
            php: 8.1
          - laravel: 6.*
            php: 8.1

    name: ${{ matrix.php }} - ${{ matrix.statamic }} - ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Yeet out the composer lock file
        run: rm composer.lock

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      # - name: Set PHP 7.4 Mockery
      #   run: composer require "mockery/mockery:>=1.2.3" --no-interaction --no-update
      #   if: matrix.php >= 7.4 && matrix.php <8.0

      # - name: Set PHP 8 Mockery
      #   run: composer require "mockery/mockery:>=1.3.3" --no-interaction --no-update
      #   if: matrix.php >= 8.0

      # - name: Set PHP 8.1 Testbench
      #   run: composer require "orchestra/testbench:^6.22.0" --no-interaction --no-update
      #   if: matrix.laravel == '8.*' && matrix.php >= 8.1

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "statamic/cms:${{ matrix.statamic }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --no-interaction

      - name: Run PHPUnit
        run: composer test
